export const ROUTES = {
  HOME: "/",
  ABOUT: "/about",
  CONTACT: "/contact",
  SERVICE: "/service",
  CAREER: "/career",
  TRACK_SHIPMENT: "/trackshipment",
  MEDIACENTER: "/media-center",
  PRIVACY_POLICY: "/privacy-policy",
  PACKAGING: "/packaging",
  ERROR_404: "/not-found",
  SOCIAL_NETWORK: "/socialnetwork",
  DAMAGE_FREE_DELIVERY: "/damage-free-delivery",
  TECH_DRIVEN_SOLUTION: "/tech-driven-solution",

  MULTIMODAL_TRANSPORTATION: "/multimodal-transport",
  WAREHOUSE_SOLUTION: "/warehouse-solution",
  PACKAGING_SOLUTION: "/packaging-solution",
  THREEPL_INVENTORY_MANAGEMENT: "/3pl-inventory-management",
  FOURPL_INPLANT_LOGISTICS_PROJECT_MANAGEMENT:
    "/4pl-inplant-logistics-project-management",

  PACKAGING_PRODUCTS: "/packaging-products",
  PP_BOX: "/pp-box",
  FOLDABLE_CRATES_BIN: "/foldable-crates-bin",
  PLS_FOLDABLE: "/pls-foldable",
  FLC_FOLDABLE: "/flc-foldable",
  WIRE_MESH_CONTAINER: "/wire-mesh-container",
  METAL_FOLDABLE_BIN: "/metal-foldable-bin",
  PALLETS: "/pallets",
  PLASTIC_PALLETS: "/plastic-pallets",
  STEEL_PALLETS: "/steel-pallets",
  WOODEN_PALLETS: "/wooden-pallets",
  THERMOFORMING_TRAYS: "/thermoforming-trays",
  CUSTOMIZE_WOODEN_PACKAGING_BOX: "/customize-wooden-packaging-box",

  AIR_SERVICE: "/air-service",
  RAIL_SERVICE: "/rail-service",
  ROAD_SERVICE: "/road-service",
};
